const products = [
  {
    id: 0,
    name: "Syltherine",
    category: "Living room",
    description: "Stylish cafe chair with modern design",
    price: "$2,500.00",
    oldPrice: "$3,500.00",
    tag: "30%",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFu6kaux390zQTcYXp_ax2SkSGp4exQrlw9Q&s",
  },
  {
    id: 1,
    name: "Leviosa",
    category: "Living room",
    description: "Contemporary cafe chair with ergonomic support",
    price: "$2,500.00",
    oldPrice: "",
    tag: "",
    img: "https://mysleepyhead.com/media/catalog/product/s/l/sleepyhead_product_ls10186.jpg",
  },
  {
    id: 2,
    name: "Lolito",
    category: "Living room",
    description: "Luxury big sofa with premium cushions",
    price: "$500.00",
    oldPrice: "$700.00",
    tag: "60%",
    img: "https://www.godrejinterio.com/imagestore/B2C/56101543SD00017/56101543SD00017_A2_1440x810.jpg",
  },
  {
    id: 3,
    name: "Respira",
    category: "Balcony",
    description: "Outdoor table and stool set for cozy evenings",
    price: "$500.00",
    oldPrice: "",
    tag: "New",
    img: "https://rukminim2.flixcart.com/image/850/1000/k47cgi80/dining-set/f/g/k/8-seater-brown-rosewood-sheesham-hhfk-17-hariom-handicraft-original-imafn66rskcnv96g.jpeg",
  },
  {
    id: 4,
    name: "Grifo",
    category: "Bedroom",
    description: "Night lamp with wooden base and soft light",
    price: "$150.00",
    oldPrice: "",
    tag: "",
    img: "https://rajhandicraft.com/cdn/shop/products/RH3125LTbest-online-sheesham-solid-wood-wooden-furniture-couch-sofa_16_grande.jpg",
  },
  {
    id: 5,
    name: "Muggo",
    category: "Kitchen",
    description: "Small ceramic mug with glossy finish",
    price: "$100.00",
    oldPrice: "",
    tag: "New",
    img: "https://www.thespruce.com/thmb/65l9i7kdcdic4mVKvKykx1Bq6bs=/3360x0/filters:no_upscale():max_bytes(150000):strip_icc()/signs-to-replace-your-couch-4165258-hero-5266fa7b788c41f6a02f24224a5de29b.jpg",
  },
  {
    id: 6,
    name: "Pingky",
    category: "Child bedroom",
    description: "Cute bed set with colorful pillows",
    price: "$1,000.00",
    oldPrice: "$1,400.00",
    tag: "60%",
    img: "https://m.media-amazon.com/images/I/919UESmmiLL.jpg",
  },
  {
    id: 7,
    name: "Potty",
    category: "Balcony",
    description: "Minimalist flower pot for modern spaces",
    price: "$500.00",
    oldPrice: "",
    tag: "New",
    img: "https://media.designcafe.com/wp-content/uploads/2023/04/03120224/space-saving-design-solutions-in-hyderabad-with-tv-unit-and-mandir.jpg",
  },
  {
    id: 8,
    name: "DinePro Table",
    category: "Kitchen",
    description: "6-seater dining table in walnut finish",
    price: "$750.00",
    oldPrice: "$900.00",
    tag: "20%",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtQhTx_kf5nxQOF9fjyehjGxy1qbyfGIeUmw&s",
  },
  {
    id: 9,
    name: "CloudRest Mattress",
    category: "Bedroom",
    description: "Soft queen-size mattress with memory foam",
    price: "$400.00",
    oldPrice: "$600.00",
    tag: "New",
    img: "https://springtek.in/images/product/154/CoirBond_1359_01.jpg?v=1",
  },
  {
    id: 10,
    name: "Brighty Study Desk",
    category: "Child bedroom",
    description: "Compact wooden study desk for kids",
    price: "$300.00",
    oldPrice: "$400.00",
    tag: "",
    img: "https://m.media-amazon.com/images/I/71fNfkZiUIL.jpg",
  },
  {
    id: 11,
    name: "TeaTime Kettle",
    category: "Kitchen",
    description: "Electric glass kettle with auto shut-off",
    price: "$80.00",
    oldPrice: "$120.00",
    tag: "30%",
    img: "https://rukminim3.flixcart.com/image/850/1000/xif0q/electric-kettle/h/o/i/electric-kettle-1-5-litre-electric-kettle-1-5-litre-stainless-original-imagpyg5ggfbnnpg.jpeg?q=90&crop=false",
  },
  {
    id: 12,
    name: "Luna Bookshelf",
    category: "Living room",
    description: "Wooden bookshelf with modern angled design",
    price: "$450.00",
    oldPrice: "",
    tag: "New",
    img: "https://preview.redd.it/cmktz3g4o7y51.jpg?width=1080&crop=smart&auto=webp&s=62edb242d526ee55f3584833a2e46bb657c4d173",
  },
  {
    id: 13,
    name: "Aura Wall Clock",
    category: "Living room",
    description: "Modern wall clock with silent movement",
    price: "$120.00",
    oldPrice: "$180.00",
    tag: "30%",
    img: "https://m.media-amazon.com/images/I/41-2t5t7apL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 14,
    name: "Cozy Blanket",
    category: "Bedroom",
    description: "Plush microfiber blanket for winter nights",
    price: "$90.00",
    oldPrice: "",
    tag: "New",
    img: "https://www.jaipurfabric.com/cdn/shop/files/ddh2611-831744_l.jpg?v=1747143874",
  },
  {
    id: 15,
    name: "Bamboo Plant Stand",
    category: "Balcony",
    description: "Eco-friendly plant stand for indoor/outdoor",
    price: "$70.00",
    oldPrice: "$100.00",
    tag: "30%",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeyYHvuOO09mruT-FXy0h29o5cAGmUxJmr8g&s",
  },
  {
    id: 16,
    name: "Mini Storage Shelf",
    category: "Child bedroom",
    description: "Toy and book shelf for kids",
    price: "$160.00",
    oldPrice: "$200.00",
    tag: "20%",
    img: "https://rukminim2.flixcart.com/image/850/1000/xif0q/cabinet-drawer/4/t/r/39-pp-42-7-08-8904423911801-cello-brown-85-5-4-original-imagw82njmmza4tx.jpeg?q=90&crop=false",
  },
  {
    id: 17,
    name: "ChefPro Knife Set",
    category: "Kitchen",
    description: "Professional 6-piece kitchen knife set",
    price: "$60.00",
    oldPrice: "$85.00",
    tag: "New",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPKiLvScgdntbSEQ13twExf4qiFFdhfCJ45w&s",
  },
  {
    id: 18,
    name: "Retro Armchair",
    category: "Living room",
    description: "Retro-style fabric armchair with wooden legs",
    price: "$650.00",
    oldPrice: "$800.00",
    tag: "New",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTReXt-MAtMaRBFqK80NhBO4yv1GjmMA3yTqg&s",
  },
  {
    id: 19,
    name: "Dreamland Bunk Bed",
    category: "Child bedroom",
    description: "Wooden bunk bed with ladder and guard rails",
    price: "$1,200.00",
    oldPrice: "$1,500.00",
    tag: "20%",
    img: "https://aicdn.speedsize.com/aa3a6307-a6a2-4e37-b0c1-7edf9ef7face/www.bedkingdom.co.uk/media/catalog/product/d/r/dreamland0015_copy_1.jpg?speedsize=w_590",
  }
];

export default products;

// const products = [
//   {
//     id: 0,
//     name: "Syltherine",
//     category: "Living room - Stylish cafe chair",
//     price: "$2,500.00",
//     oldPrice: "$3,500.00",
//     tag: "30%",
//     img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFu6kaux390zQTcYXp_ax2SkSGp4exQrlw9Q&s",
//   },
//   {
//     id: 1,
//     name: "Leviosa",
//     category: "Living room - Stylish cafe chair",
//     price: "$2,500.00",
//     oldPrice: "",
//     tag: "",
//     img: "https://mysleepyhead.com/media/catalog/product/s/l/sleepyhead_product_ls10186.jpg",
//   },
//   {
//     id: 2,
//     name: "Lolito",
//     category: "Living room - Luxury big sofa",
//     price: "$500.00",
//     oldPrice: "$700.00",
//     tag: "60%",
//     img: "https://www.godrejinterio.com/imagestore/B2C/56101543SD00017/56101543SD00017_A2_1440x810.jpg",
//   },
//   {
//     id: 3,
//     name: "Respira",
//     category: "Balcony - Outdoor table and stool",
//     price: "$500.00",
//     oldPrice: "",
//     tag: "New",
//     img: "https://rukminim2.flixcart.com/image/850/1000/k47cgi80/dining-set/f/g/k/8-seater-brown-rosewood-sheesham-hhfk-17-hariom-handicraft-original-imafn66rskcnv96g.jpeg",
//   },
//   {
//     id: 4,
//     name: "Grifo",
//     category: "Bedroom - Night lamp",
//     price: "$150.00",
//     oldPrice: "",
//     tag: "",
//     img: "https://rajhandicraft.com/cdn/shop/products/RH3125LTbest-online-sheesham-solid-wood-wooden-furniture-couch-sofa_16_grande.jpg",
//   },
//   {
//     id: 5,
//     name: "Muggo",
//     category: "Kitchen - Small mug",
//     price: "$100.00",
//     oldPrice: "",
//     tag: "New",
//     img: "https://www.thespruce.com/thmb/65l9i7kdcdic4mVKvKykx1Bq6bs=/3360x0/filters:no_upscale():max_bytes(150000):strip_icc()/signs-to-replace-your-couch-4165258-hero-5266fa7b788c41f6a02f24224a5de29b.jpg",
//   },
//   {
//     id: 6,
//     name: "Pingky",
//     category: "Child bedroom - Cute bed set",
//     price: "$1,000.00",
//     oldPrice: "$1,400.00",
//     tag: "60%",
//     img: "https://m.media-amazon.com/images/I/919UESmmiLL.jpg",
//   },
//   {
//     id: 7,
//     name: "Potty",
//     category: "Balcony - Minimalist flower pot",
//     price: "$500.00",
//     oldPrice: "",
//     tag: "New",
//     img: "https://media.designcafe.com/wp-content/uploads/2023/04/03120224/space-saving-design-solutions-in-hyderabad-with-tv-unit-and-mandir.jpg",
//   },
//   {
//     id: 8,
//     name: "DinePro Table",
//     category: "Kitchen - Dining table",
//     price: "$750.00",
//     oldPrice: "$900.00",
//     tag: "20%",
//     img: "https://www.ulcdn.net/images/products/674921/product/Cohoon_6_Seater_Dining_Table_Walnut_EC_Main.jpg",
//   },
//   {
//     id: 9,
//     name: "CloudRest Mattress",
//     category: "Bedroom - Soft mattress",
//     price: "$400.00",
//     oldPrice: "$600.00",
//     tag: "New",
//     img: "https://images.woodenstreet.de/image/cache/data%2Fbedroom-furniture%2Fmattresses%2Fmattress-type%2Fqueen-size-mattress%2Fqueen-size-mattress-in-6-inch%2Fmemory-foam%2Froyal-comfort%2Fwhite%2Fupdated%2F1-810x702.jpg",
//   },
//   {
//     id: 10,
//     name: "Brighty Study Desk",
//     category: "Child bedroom - Study table",
//     price: "$300.00",
//     oldPrice: "$400.00",
//     tag: "",
//     img: "https://5.imimg.com/data5/YQ/QK/MY-33582074/kids-study-table.jpg",
//   },
//   {
//     id: 11,
//     name: "TeaTime Kettle",
//     category: "Kitchen - Electric kettle",
//     price: "$80.00",
//     oldPrice: "$120.00",
//     tag: "30%",
//     img: "https://www.kent.co.in/images/product/kitchen-appliances/electric-kettle/KENT-Electric-Kettle-Glass-16051.png",
//   },
//   {
//     id: 12,
//     name: "Luna Bookshelf",
//     category: "Living room - Wooden bookshelf",
//     price: "$450.00",
//     oldPrice: "",
//     tag: "New",
//     img: "https://images.woodenstreet.de/image/data/bookshelves/pinto-bookshelf/pinto-bookshelf-right-angle-view-woodenstreet.jpg",
//   }
// ];

// export default products;
