
const subcategoriesMap = {
  Kitchen: {
    "Cabinet Finishes": [
      {
        name: "1mm Decorative laminates",
        image: "/images/subcategories/1mm.jpeg"
      },
      "Wood Look Laminates",
      "Acrylic Laminates",
      {
        name: "Solid Color Laminates",
        image: 'https://5.imimg.com/data5/SELLER/Default/2022/4/VM/OB/DU/29839102/solid-color-laminate.jpg',
      },
      "Edge Banding",
      "Liner Laminates",
      {
        name: "Fabric Laminates",
        image: "https://5.imimg.com/data5/FQ/FP/VM/SELLER-66939695/fabric-laminate-sheet.jpg"
      }, "Marble Look Laminates",
      "Wood Veneers",
    ],
    Countertops: ["Quartz Countertops", "Vitrified Slabs", "Corian"],
    "Tiles and Backsplashes": [
      "Subway Tiles",
      "Moroccan Tiles",
      "Mosaic Tiles",
      "Anti-skid Tiles",
      "Digital Print Tiles",
      "Glass Highlighter Tiles",
      "Athangudi Tiles",
      "3D Tiles",
      "Wood Look Tiles",
      "Handcrafted Tiles",
      "Wooden Flooring",
    ],
    Cabinetry: [
      "Water Proof and Water Resistant Ply",
      "MDF",
      "HDHMR Boards",
      "HDF",
      "Prelam Boards",
      "Acrylic Boards",
      "12 mm Water Proof Ply",
      "16 mm Water Proof Ply",
      "18 mm Water Proof Ply",
      "6 mm Water Proof Ply",
    ],
  },
  Laminates: {
    "Shop by Category": [
      "Browse All",
      "Decorative Laminates",
      "Acrylic Laminates",
      "Liner Laminates",
      "Edgebands",
      {
        name: "HPL Sheets",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/2/OH/WD/PL/3487402/hpl-sheet-high-pressure-laminate-sheet.jpg",
      },
      "PVC Laminates",
      "Corian",
    ],
    "Shop by Look": [
      "Cane Laminates",
      "Fluted Acrylic",
      "Solid Colour Laminates",
      "Wood Laminates",
      "Marble & Stone Laminates",
      "Fabric Laminates",
      "Leather Laminates",
      {
        name: "Metallic Laminates",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrtlki55WSFnArefbEf6b4CM17WdS8KgeeWw&s"
      },
      "Fluted Laminates",
      "Patterned Laminates",
      "Rustic Look",
    ],
    "Shop by Finish & Thickness": [
      "Suede Finish Laminates",
      "PU Finish Laminates",
      "Texture Finish Laminates",
      "Leather Finish Laminates",
      "Glossy Finish Laminates",
      "Matte Finish Laminates",
      "1 mm Decorative Laminates",
      "0.8 mm Decorative Laminates",
      "0.92 mm Decorative Laminates",
      "0.72 mm Liner Laminates",
      "1.5 mm Acrylic Laminates",
      "1 mm Acrylic Laminates",
    ],
    "Shop by Colour": [
      "Shade of Beige",
      "Shades of Grey",
      "Shades of Pink",
      "Shades of White",
      "Shades of Blue",
      "Shades of Green",
      "Shades of Brown",
      "Shades of Yellow",
      "Shades of Wood",
    ],
  },
  Wardrobe: {
    "Wardrobe Finishes": [
      "1 mm Laminates",
      "Acrylic Laminates",
      "Solid Colour Laminates",
      "Marble Look Laminates",
      {
        name: "Engraved Acrylic Panels",
        image: "https://d68pxkftt5390.cloudfront.net/image/e6c6306c-7a55-412a-bcd9-aac20cc4f2f9.png"
      },

      "Fluted Laminates",
      "Leather Laminates",
      "Wood Look Laminates",
      "Fluted Acrylic",
      "Cane Laminates",
      "PVC Laminates",
      "Wardrobe Edgebanding",
      "Abstract Patterns",
    ],
    "Wardrobe Cabinetry": [
      "Plywood",
      {
        name: "Blockboard",
        image: "https://artechpro.com/media/catalog/product/cache/1caa554d4ef407fe569c81ce13f2a21c/1/4/1442B-NP_3.jpg"
      },
      "MDF",
      "HDF",
      "HDHMR",
      "Particle Board",
      "Prelam Boards",
      "18mm & 16mm ply",
      "Acrylic Board",
      "Neem Ply",
    ],
    "Wardrobe Veneers": ["Wood Veneers", "Stone Veneers"],
    "Wardrobe Curated Collections": [
      "Economy Laminates under 1199",
      "Premium Laminates from 1999",
      "Acrylic Laminates under 3500",
      "Bendable PVC Laminates",
    ],
  },
  Flooring: {
    "Shop by Application": [
      {
        name: "Wall Tiles",
        image: "https://d91ztqmtx7u1k.cloudfront.net/ClientContent/Images/Medium/20220202085823-24843056-a450-4171-b09e-ace9651c9d00.jpg"
      },
      "Floor Tiles",
      "Bedroom Tiles",
      "Living Room Tiles",
      "Bathroom Tiles",
      "Kitchen Tiles",
      "Elevation Tiles",
      "Parking Tiles",
    ],
    "Wooden Flooring": [
      "Laminate Wood Floor",
      "SPC Floor",
      {
        name: "Vinyl Floor",
        image: "https://images-cdn.ubuy.co.in/633ae0c05182be040d68c306-livelynine-reclaimed-wood-vinyl-flooring.jpg"
      },
      "Solid Wood Floor",
      "Engineered Wood Floor",
    ],
    "Shop by Look": [
      "Tropical Tiles",
      "Terrazzo Tiles",
      "Marble Look Tiles",
      "Wood Look Tiles",
      "Subway Tiles",
      "Highlighter Tiles",
      "Solid Colour",
      "Stacked Stone Tiles",
      "Moroccan Tiles",
      "Mosaic Tiles",
      "Patterned Tiles",
      "Brick Look Tiles",
      "Endless Tiles",
    ],
    "Shop by Size": [
      "2ft x 2ft (600 x 600 mm)",
      "2ft x 4ft (600 x 1200 mm)",
      "1ft x 2ft (300 x 600 mm)",
      "1ft x 1.5ft (300 x 450 mm)",
      "4ft x 6ft (1200 x 1800 mm)",
    ],
    "Shop by Finish": [
      "Glossy Finish Tiles",
      "Matte Finish Tiles",
      "Rustic Finish Tiles",
      "Carving Finish Tiles",
      "Punch Finish Tiles",
      "Metallic Finish Tiles",
    ],
    "Shop by Material": [
      "Vitrified Tiles",
      "Ceramic Tiles",
      "Porcelain Tiles",
      "Stone Cladding",
    ],
    "Shop by Category": [
      "Browse All",
      "GVT Tiles",
      "PGVT Tiles",
      "Full Body Tiles",
      "Digital Tiles",
      "Double Charge Tiles",
      "Concrete Tiles",
      "Carpet Tiles",
      "Ceiling Tiles",
    ],
  },
  LouversandPanels: {
    "Shop by Type": [
      "Browse All",
      "Louvers",
      "Decorative Wall Panel",
      "Exterior Wall Panel",
      "Engraved Acrylic Panels",
      "Onyx",
      "PU Stone Panels",
      "3D Wall Panel",
      "Acrylic Resin Panel",
      "Alabaster Sheets",
      "Stone Veneer",
    ],
    "Shop by Look": [
      "Wood Look Panels",
      "Marble & Stone Look Panels",
      "Solid Colour Panels",
      "Geometric Design Panels",
      "Patterned Look Panels",
      "Luxury Design Panels",
    ],
    "Shop by Material": [
      "Charcoal Panels",
      "MDF Panels",
      "WPC Panels",
      "PVC Panels",
      "Solid Wood Panels",
      "HDHMR Panels",
      "HDF Panels",
    ],
    "Shop by Colour": [
      {
        name: "White Panels",
        image: "https://images.jdmagicbox.com/quickquotes/images_main/pvc-louvers-wall-panel-white-5-10-mm-2226610806-itjko6az.jpg"
      },
      "Beige Panels",
      {
        name: "Blue Panels",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFoNEdJ1iVh8NkKsQV0uoJMpYT95-O-Cs6tQ&s"
      },
      "Grey Panels",
      "Brown Panels",
      "Yellow Panels",
      "Pink Panels",
      "Green Panels",
    ],
  },
  Bathroom: {
    "Shop by Type": [
      "Vanity Units",
      {
        name: "Bathroom Cabinets",
        image: 'https://m.media-amazon.com/images/I/716e4MRHJIL._UF350,350_QL80_.jpg',
      },
      "Mirror Cabinets",
      "Countertops",
      {
        name: "Shower Panels",
        image: 'https://www.jaquar.com/images/thumbs/0032808_curve-neo_300.jpeg'
      },

      "Wall Panels",
      "Storage Units",
    ],
    "Shop by Material": [
      "PVC Cabinets",
      "WPC Cabinets",
      "MDF Cabinets",
      "Solid Wood Cabinets",
    ],
    "Shop by Look": [
      "Marble Look Cabinets",
      "Solid Colour Cabinets",
      "Wood Look Cabinets",
      "Glossy Finish Cabinets",
      "Matte Finish Cabinets",
    ],
    "Shop by Size": [
      "2ft Units",
      "3ft Units",
      "4ft Units",
      "Custom Size Units",
    ],
  },
  Wallpaper: {
    "Shop by Type": [
      "Browse All",
      {
        name: "3D Wallpapers",
        image: "https://img2.exportersindia.com/product_images/bc-full/2023/9/3466624/matte-white-and-blue-3d-designer-wallpaper-1684823680-6906235.jpeg"
      },
      "Textured Wallpapers",
      {
        name: "Kids Wallpapers",
        image: "https://4.imimg.com/data4/LJ/EQ/MY-8271179/kids-wallpapers.jpg",
      },
      "Floral Wallpapers",
      "Geometric Wallpapers",
      "Nature Wallpapers",
      "Brick Wallpapers",
      "Abstract Wallpapers",
    ],
    "Shop by Material": [
      "PVC Wallpapers",
      "Vinyl Wallpapers",
      "Non-Woven Wallpapers",
      "Paper Wallpapers",
      "Fabric Wallpapers",
    ],
    "Shop by Room": [
      "Living Room Wallpapers",
      "Bedroom Wallpapers",
      "Kids Room Wallpapers",
      "Dining Room Wallpapers",
      "Office Wallpapers",
    ],
    "Shop by Colour": [
      "White",
      "Beige",
      "Blue",
      "Grey",
      "Yellow",
      "Pink",
      "Green",
      "Brown",
      "Black",
    ],
  },
  Outdoor: {
    "Shop by Type": [
      "Browse All",
      "Water Proof Plywood",
      "12mm Water Proof Ply",
      "18mm Water Proof Ply",
      "16mm Water Proof Ply",
    ],
  },
  TVUnit: {
    "Shop by Type": [
      "Browse All",
      {name:"Cabinetry",
        image:"https://images.woodenstreet.de/image/cache/data/Hanks-TV+Unit/2-810x702.jpg",
      },
      "Water Proof Plywood",
      "12mm Water Proof Ply",
      "WPC Board",
    ],
  },
};
export default subcategoriesMap;